import type { Campaign } from "@prisma/client";

// Fábrica de Campaign "de mentira" para testes puros (sem tocar no banco).
export function makeCampaign(overrides: Partial<Campaign> = {}): Campaign {
  return {
    id: "camp_test",
    clientId: "client_test",
    name: "Campanha teste",
    description: null,
    campaignType: "evento",
    status: "DISCOVERY",
    primaryObjective: null,
    secondaryObjectives: "[]",
    startDate: null,
    endDate: null,
    eventDate: null,
    eventTime: null,
    eventLocation: null,
    eventFormat: null,
    eventCapacity: null,
    eventIsPaid: null,
    eventPrice: null,
    audience: null,
    audienceSegments: "[]",
    region: null,
    targetResult: null,
    targetMetricLabel: null,
    adBudget: null,
    creativeBudget: null,
    physicalBudget: null,
    partnerBudget: null,
    otherBudget: null,
    budgetRangeLabel: null,
    valueProposition: null,
    cta: null,
    ctaLink: null,
    landingSubtitle: null,
    bannerImageUrl: null,
    channels: "[]",
    assetsAvailable: "[]",
    constraints: "[]",
    briefingExtra: "{}",
    briefingComplete: false,
    briefingMissing: "[]",
    createdAt: new Date(),
    updatedAt: new Date(),
    ...overrides,
  };
}
